# This is a basic workflow to help you get started with Actions

name: Deploy site

on:
  workflow_run:
    workflows: ["Build site"]
    branches: ["master"]
    types: [completed]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        workflow: main.yml
        workflow_conclusion: success
        name: production-files
        path: ./build
    
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: "d091515d-bf2b-4207-b1ee-2932dd43b6ed"
        tenant-id: "da419ccd-8206-427d-8e7e-78cb6fb5ca6d"
        subscription-id: "dbe9f787-2fe7-4406-b528-4dcff64b8bcd"
    
    - name: Upload to Azure blob storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
            az storage blob upload-batch --account-name craazstoragedemo48765 -d '$web' -s ./production-files
    
    - name: Azure logout
      run: |
            az logout
